AWSTemplateFormatVersion: 2010-09-09
Description: 'EKS Managed Nodes (SSH access: false) [created by eksctl]'
Mappings:
  ServicePrincipalPartitionMap:
    aws:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-cn:
      EC2: ec2.amazonaws.com.cn
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
    aws-us-gov:
      EC2: ec2.amazonaws.com
      EKS: eks.amazonaws.com
      EKSFargatePods: eks-fargate-pods.amazonaws.com
Resources:
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              Iops: 3000
              Throughput: 125
              VolumeSize: 80
              VolumeType: gp3
        MetadataOptions:
          HttpPutResponseHopLimit: 2
          HttpTokens: optional
        SecurityGroupIds:
          - !ImportValue 'eksctl-cluster-5-cluster::ClusterSecurityGroupId'
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: cluster-5-ng3-private-b-Node
              - Key: alpha.eksctl.io/nodegroup-name
                Value: ng3-private-b
              - Key: alpha.eksctl.io/nodegroup-type
                Value: managed
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: cluster-5-ng3-private-b-Node
              - Key: alpha.eksctl.io/nodegroup-name
                Value: ng3-private-b
              - Key: alpha.eksctl.io/nodegroup-type
                Value: managed
          - ResourceType: network-interface
            Tags:
              - Key: Name
                Value: cluster-5-ng3-private-b-Node
              - Key: alpha.eksctl.io/nodegroup-name
                Value: ng3-private-b
              - Key: alpha.eksctl.io/nodegroup-type
                Value: managed
        UserData: >-
          TUlNRS1WZXJzaW9uOiAxLjANCkNvbnRlbnQtVHlwZTogbXVsdGlwYXJ0L21peGVkOyBib3VuZGFyeT1hMDhlZTIxNWQ0ZjFjNDhiY2IzODg4ZjVjYzA4MjAzOWYyMWI4ZGFjODQzMGQzNzVhODA4ZmJlOGVhZjYNCg0KLS1hMDhlZTIxNWQ0ZjFjNDhiY2IzODg4ZjVjYzA4MjAzOWYyMWI4ZGFjODQzMGQzNzVhODA4ZmJlOGVhZjYNCkNvbnRlbnQtVHlwZTogdGV4dC94LXNoZWxsc2NyaXB0DQpDb250ZW50LVR5cGU6IGNoYXJzZXQ9InVzLWFzY2lpIg0KDQpmb3IgbiBpbiAkKGNhdCAvc3lzL2RldmljZXMvc3lzdGVtL2NwdS9jcHUqL3RvcG9sb2d5L3RocmVhZF9zaWJsaW5nc19saXN0IHwgY3V0IC1zIC1kLCAtZjItIHwgdHIgJywnICcKJyB8IHNvcnQgLXVuKTsgZG8gZWNobyAwID4gL3N5cy9kZXZpY2VzL3N5c3RlbS9jcHUvY3B1JHtufS9vbmxpbmU7IGRvbmUNCi0tYTA4ZWUyMTVkNGYxYzQ4YmNiMzg4OGY1Y2MwODIwMzlmMjFiOGRhYzg0MzBkMzc1YTgwOGZiZThlYWY2LS0NCg==
      LaunchTemplateName: !Sub '${AWS::StackName}'
  ManagedNodeGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      AmiType: AL2_x86_64
      ClusterName: cluster-5
      InstanceTypes:
        - c3.8xlarge
      Labels:
        alpha.eksctl.io/cluster-name: cluster-5
        alpha.eksctl.io/nodegroup-name: ng3-private-b
        nodegroup-type: very-special-science-workloads
      LaunchTemplate:
        Id: !Ref LaunchTemplate
      NodeRole: !GetAtt 
        - NodeInstanceRole
        - Arn
      NodegroupName: ng3-private-b
      ScalingConfig:
        DesiredSize: 4
        MaxSize: 4
        MinSize: 4
      Subnets:
        - subnet-06c811c0f43d194c0
      Tags:
        alpha.eksctl.io/nodegroup-name: ng3-private-b
        alpha.eksctl.io/nodegroup-type: managed
      Taints:
        - Effect: NO_SCHEDULE
          Key: special
          Value: 'true'
  NodeInstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - !FindInMap 
                  - ServicePrincipalPartitionMap
                  - !Ref 'AWS::Partition'
                  - EC2
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Sub >-
          arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Path: /
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/NodeInstanceRole'
