# An example of ClusterConfig object enabling gitops Flux v2
# in a cluster:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-12
  region: ap-southeast-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1

gitops:
  flux:
    gitProvider: github             # required. options are github or gitlab
    flags:                          # required. arbitrary map[string]string for all flux args.
    # these args are not controlled by eksctl. see https://fluxcd.io/docs/get-started/ for all available flags
      owner: "jgyy"
      repository: "eks-paulo"
      private: "false"
      personal: "true"
      branch: "main"
      namespace: "flux-system"
      path: ""
