# An example of encrypting worker root volumes
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-10
  region: ap-southeast-1

managedNodeGroups:
  - name: ng1-encrypt-using-default-kms-key
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
  - name: ng2-encrypt-using-customer-encrytion-key
    instanceType: m5.xlarge
    desiredCapacity: 1
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    # volumeKmsKeyID: 0f494c69-aab4-49a7-9c3a-51d292b7fb2a
    # please see https://docs.aws.amazon.com/autoscaling/ec2/userguide/key-policy-requirements-EBS-encryption.html for service-linked role permissions
