# An example of ClusterConfig object with access to CSI drivers:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-6
  region: ap-southeast-1

managedNodeGroups:
  - name: ng-1
    instanceType: m5.large
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
