# An example of ClusterConfig showing different ways of setting nodegroup SSH keys:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-7
  region: ap-southeast-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import public key from file
      publicKeyPath: "~/.ssh/id_rsa_tests.pub"
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import default public key (~/.ssh/id_rsa.pub)
      allow: true
  - name: ng-3
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
  - name: ng-4
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # import inline public key
      publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD0EKrP4pAUj38dH+d7qDw9lKhpA1UKs8g18NwoNdGukLtHhhkTxXWibXZYGfQpbfx5TuFgY6v20AARd7+uQJuA5O2Rb39gAWQqQPK85SN46jaPhVa7NUktEwhjRNrbWahc0Yph9sJkVxFjKSswoD1LXb85tAsrtAPJ8pubx/8facRLbWZP3BJr3DOoDQPzh1nghizFios+dmlMj1xur+mIdn9Ha3nYvktk72ACnnoNqyCi2n2cbLE2J8niDRFfbilfqo9R/X3cBZQ28nyUwqsP/5ZM8A5KCmsQCNA3BcQB1DnV1k54fHaAFZjp781qPBi13rSBgRUH9LmfAl7uXL47JzUm8JypTn8ApjJWNm7U+KHo1mrJb74ZnWnkVmyrXYQAH+0jJQWhUO1eZvehHmKUwOdrj34XUV7O7Vxotgmh9+waXb0PpBtMndElpk7mksJSrTii4gWnTRhk3mzKe+rfqDVvUw1eS3BKNqTxyqqv+CtvbKinDtIPWUIfx9kYJE= jgyy@Jeffreys-MacBook-Pro.local"
  - name: ng-5
    instanceType: m5.large
    desiredCapacity: 1
    ssh: # use existing EC2 key but don't allow SSH access to nodegroup (security group is not created to allow SSH access).
      publicKeyName: ec2_dev_key
      allow: false
  - name: ng-6
    instanceType: m5.large
    desiredCapacity: 1
    ssh:
      enableSsm: true
  - name: ng-7
    instanceType: m5.large
    desiredCapacity: 1
    # no SSH
