# An example of ClusterConfig object with custom VPC IPv4 CIDR,
# and auto-allocated IPv6 CIDRs for all subnets; added in managed node groups for testing
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-2
  region: ap-southeast-1

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: true
  # enable public access to endpoint for testing
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
  - name: ng-2
    instanceType: m5.large
    desiredCapacity: 1
