AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for serviceaccount "ci-cd/build-service" [created and managed
  by eksctl]
Resources:
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:aud: sts.amazonaws.com
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:sub: system:serviceaccount:ci-cd:build-service
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::473359703960:oidc-provider/oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn