AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for serviceaccount "kube-system/efs-csi-controller-sa" [created
  and managed by eksctl]
Resources:
  PolicyEFSCSIController:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyEFSCSIController"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - elasticfilesystem:DescribeAccessPoints
          - elasticfilesystem:DescribeFileSystems
          Effect: Allow
          Resource: "*"
        - Action:
          - elasticfilesystem:CreateAccessPoint
          Condition:
            StringLike:
              aws:RequestTag/efs.csi.aws.com/cluster: 'true'
          Effect: Allow
          Resource: "*"
        - Action:
          - elasticfilesystem:DeleteAccessPoint
          Condition:
            StringLike:
              aws:ResourceTag/efs.csi.aws.com/cluster: 'true'
          Effect: Allow
          Resource: "*"
        Version: '2012-10-17'
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:aud: sts.amazonaws.com
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:sub: system:serviceaccount:kube-system:efs-csi-controller-sa
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::473359703960:oidc-provider/oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01
        Version: '2012-10-17'
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn