AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for serviceaccount "kube-system/external-dns" [created and managed
  by eksctl]
Resources:
  PolicyExternalDNSChangeSet:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyExternalDNSChangeSet"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - route53:ChangeResourceRecordSets
          Effect: Allow
          Resource:
            Fn::Sub: arn:${AWS::Partition}:route53:::hostedzone/*
        Version: '2012-10-17'
  PolicyExternalDNSHostedZones:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyExternalDNSHostedZones"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - route53:ListHostedZones
          - route53:ListResourceRecordSets
          - route53:ListTagsForResource
          Effect: Allow
          Resource: "*"
        Version: '2012-10-17'
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:aud: sts.amazonaws.com
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:sub: system:serviceaccount:kube-system:external-dns
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::473359703960:oidc-provider/oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01
        Version: '2012-10-17'
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn