AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for serviceaccount "kube-system/ebs-csi-controller-sa" [created
  and managed by eksctl]
Resources:
  PolicyEBSCSIController:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyEBSCSIController"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - ec2:CreateSnapshot
          - ec2:AttachVolume
          - ec2:DetachVolume
          - ec2:ModifyVolume
          - ec2:DescribeAvailabilityZones
          - ec2:DescribeInstances
          - ec2:DescribeSnapshots
          - ec2:DescribeTags
          - ec2:DescribeVolumes
          - ec2:DescribeVolumesModifications
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:CreateTags
          Condition:
            StringEquals:
              ec2:CreateAction:
              - CreateVolume
              - CreateSnapshot
          Effect: Allow
          Resource:
          - Fn::Sub: arn:${AWS::Partition}:ec2:*:*:volume/*
          - Fn::Sub: arn:${AWS::Partition}:ec2:*:*:snapshot/*
        - Action:
          - ec2:DeleteTags
          Effect: Allow
          Resource:
          - Fn::Sub: arn:${AWS::Partition}:ec2:*:*:volume/*
          - Fn::Sub: arn:${AWS::Partition}:ec2:*:*:snapshot/*
        - Action:
          - ec2:CreateVolume
          Condition:
            StringLike:
              aws:RequestTag/ebs.csi.aws.com/cluster: 'true'
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:CreateVolume
          Condition:
            StringLike:
              aws:RequestTag/CSIVolumeName: "*"
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:CreateVolume
          Condition:
            StringLike:
              aws:RequestTag/kubernetes.io/cluster/*: owned
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:DeleteVolume
          Condition:
            StringLike:
              ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:DeleteVolume
          Condition:
            StringLike:
              ec2:ResourceTag/CSIVolumeName: "*"
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:DeleteVolume
          Condition:
            StringLike:
              ec2:ResourceTag/kubernetes.io/cluster/*: owned
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:DeleteSnapshot
          Condition:
            StringLike:
              ec2:ResourceTag/CSIVolumeSnapshotName: "*"
          Effect: Allow
          Resource: "*"
        - Action:
          - ec2:DeleteSnapshot
          Condition:
            StringLike:
              ec2:ResourceTag/ebs.csi.aws.com/cluster: 'true'
          Effect: Allow
          Resource: "*"
        Version: '2012-10-17'
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:aud: sts.amazonaws.com
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:sub: system:serviceaccount:kube-system:ebs-csi-controller-sa
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::473359703960:oidc-provider/oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01
        Version: '2012-10-17'
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn
