AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for serviceaccount "cert-manager/cert-manager" [created and
  managed by eksctl]
Resources:
  PolicyCertManagerChangeSet:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyCertManagerChangeSet"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - route53:ChangeResourceRecordSets
          Effect: Allow
          Resource:
            Fn::Sub: arn:${AWS::Partition}:route53:::hostedzone/*
        Version: '2012-10-17'
  PolicyCertManagerGetChange:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyCertManagerGetChange"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - route53:GetChange
          Effect: Allow
          Resource:
            Fn::Sub: arn:${AWS::Partition}:route53:::change/*
        Version: '2012-10-17'
  PolicyCertManagerHostedZones:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName:
        Fn::Sub: "${AWS::StackName}-PolicyCertManagerHostedZones"
      Roles:
      - Ref: Role1
      PolicyDocument:
        Statement:
        - Action:
          - route53:ListResourceRecordSets
          - route53:ListHostedZonesByName
          Effect: Allow
          Resource: "*"
        Version: '2012-10-17'
  Role1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:aud: sts.amazonaws.com
              oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01:sub: system:serviceaccount:cert-manager:cert-manager
          Effect: Allow
          Principal:
            Federated: arn:aws:iam::473359703960:oidc-provider/oidc.eks.ap-southeast-1.amazonaws.com/id/9CCE8A5FA3786D80C644713B35B8DB01
        Version: '2012-10-17'
Outputs:
  Role1:
    Value:
      Fn::GetAtt: Role1.Arn